export const USER_ACTION_TYPES = {
  // //Cart
  // USERS_CART: 'user/USERS_CART',
  // Add_To_Cart: 'user/ADD_TO_Cart',

  PRODUCT_SCRAP_START: 'product/PRODUCT_SCRAP_START',
  PRODUCT_SCRAP_SUCCESS: 'product/PRODUCT_SCRAP_SUCCESS',
  PRODUCT_SCRAP_FAILED: 'product/PRODUCT_SCRAP_FAILED',
};


